
CREATE DATABASE `teste` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `tab_alunos` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `nome` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO tab_alunos (nome) VALUES ('JOANA ALENCAR');
INSERT INTO tab_alunos (nome) VALUES ('PEDRO JORGE');
INSERT INTO tab_alunos (nome) VALUES ('PAULA MEDEIROS');
INSERT INTO tab_alunos (nome) VALUES ('SIMPLICIO DOS SANTOS');
INSERT INTO tab_alunos (nome) VALUES ('PAULO CESAR');
INSERT INTO tab_alunos (nome) VALUES ('HENRIQUE MATHEUS');
INSERT INTO tab_alunos (nome) VALUES ('LAURA DE ALMEIDA');

